language: node_js
node_js:
  - "8"
script: bash ./build.sh
services:
  - postgresql
  - rabbitmq
env:
  - NODE_ENV=ci
before_script:
  - psql -c 'create database bookmarks;' -U postgres
  - cd BookmarksApp
  - npm run migrate